services:
  # Backend API service
  - type: web
    name: ai-grid-backend
    env: docker
    dockerfilePath: ./backend/src/Dockerfile
    dockerContext: ./backend
    buildCommand: DOCKER_BUILDKIT=1 docker build -t ai-grid-backend:latest -f ./backend/src/Dockerfile ./backend
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: VECTOR_DB_PROVIDER
        value: milvus
      - key: OPENAI_API_KEY
        sync: false
      - key: MILVUS_DB_URI
        value: /data/milvus_db.db
      - key: TABLE_STATES_DB_URI
        value: /data/table_states.db
      - key: AUTH_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DOCKER_BUILDKIT
        value: "1"
    healthCheckPath: /ping
    disk:
      name: milvus-data
      mountPath: /data
      sizeGB: 10
    includePaths:
      - 'backend/'

  # Frontend web service
  - type: web
    name: ai-grid
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    includePaths:
      - 'frontend/'
    buildCommand: DOCKER_BUILDKIT=1 docker build -t ai-grid:latest -f ./frontend/Dockerfile ./frontend
    envVars:
      - key: VITE_API_URL
        value: https://ai-grid-backend.onrender.com
      - key: DOCKER_BUILDKIT
        value: "1"
    healthCheckPath: /
